[package]
name = "version"
version = "0.1.0"
authors = ["da-moon <damoon.azarpazhooh@ryerson.ca>"]
edition = "2018"

[dependencies]
git2={version="0.13.12",default-features=false,features=[]}
failure = "0.1.8"
quote = "1.0.7"
syn = "1.0.44"

[lib]
proc-macro = true
