[package]
name = "server"
version = "0.1.0"
authors = ["da-moon <damoon.azarpazhooh@live.com>"]
edition = "2018"
[dependencies]
actix-web = "3.1.0"
actix-rt = "1.1.1"
env_logger = "0.7.1"
serde={version="1.0.117",features=["derive"]}
serde_json = "1.0.59"
log = "0.4.11"
