name: docker-image
on:
  push:
    tags:
      - "*"
jobs:
  build:
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Build Docker Container | http-echo-rs
        id: build
        run: |
          make image
  push:
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Login to Docker Container Repository
        id: login
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image | http-echo-rs
        id: push
        run: |
          make push-image
  clean:
    needs: push
    steps:
      - name: Remove Docker Images
        id: postClean
        run: |
          docker image prune -af && \
          docker images -q | xargs -I {} docker rmi {} --force