name: docker-image
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Dependencies | http-echo-rs
        id: dependencies
        run: |
          sudo apt-get update -q && 
          sudo apt-get install build-essential libncurses5-dev libncursesw5-dev make -yq
        env:
          DEBIAN_FRONTEND: noninteractive
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Build Docker Container | http-echo-rs
        id: build
        run: |
          docker build \
          --build-arg "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" \
          --build-arg "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER" \
          --build-arg "GITHUB_ACTOR=$GITHUB_ACTOR" \
          --build-arg "GITHUB_TOKEN=$GITHUB_TOKEN" \
          -t fjolsvin/http-echo-rs:latest
          ./contrib/docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  push:
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Login to Docker Container Repository
        id: login
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image | http-echo-rs
        id: push
        run: |
          docker push fjolsvin/http-echo-rs:latest
  clean:
    runs-on: ubuntu-18.04
    needs: push
    steps:
      - name: Remove Docker Images
        id: postClean
        run: |
          docker image prune -af && \
          docker images -q | xargs -I {} docker rmi {} --force